### ISSUE TITLE
Claim error (v0.9.x)

### ISSUE THREAD

**Issue by arthuravianna** [cartesi/rollups-examples#24] opened 2023-06-29 20:57 UTC
## Expected Behavior
When the epoch finishes the Cartesi node makes the claim of the DApp current state.

## Error
The Cartesi node claim transaction is reverted. The screenshot below shows the error.
**The example running is echo-python and the network is Sepolia.**

![Captura de tela de 2023-06-28 16-29-23](https://github.com/cartesi/rollups-examples/assets/51306971/a03f4220-f030-4700-8cae-e14753aff74b)

## Steps to Reproduce
The error can be reproduced locally or in a Testnet, the two following subsections explain how to reproduce it in both cases.

### Reproduce locally
1 Select one of the rollups-examples;
2 Build the DApp;
3 Run the Cartesi node with the parameter `TX_MNEMONIC_ACCOUNT_INDEX: 1` in the dispatcher;
4 Interact with the DApp and wait for the claim. **The time can be advanced as showed in the [documentation](https://github.com/cartesi/rollups-examples#advancing-time)**

### Reproduce in Testnet
2 Select one of the rollups-examples;
2 Build the DApp;
3 Deploy it in a Testnet;
4 Run the Cartesi node;
5 Interact with the DApp and wait for the claim. **The value of the parameter RD_EPOCH_DURATION of the dispatcher can be changed to observe the claim error in a shorter time.**

## Possible cause
Since the consensus used is authority, the validator node cannot make the claim because the node is not the owner of the Authority contract, which is a requirement to execute the submitClaim method.

Authority Contract submitClaim method: https://github.com/cartesi/rollups/blob/c675c3f97ccfbf480da4c0b55007d6ad4065f806/onchain/rollups/contracts/consensus/authority/Authority.sol#L67
Cartesi Node call to submitClaim: https://github.com/cartesi/rollups/blob/c675c3f97ccfbf480da4c0b55007d6ad4065f806/offchain/dispatcher/src/sender.rs#L226

**Comment by tuler** [comment] 2023-07-06 15:28
I did not understand your expectation, as it looks you understood the cause in the "possible cause".

**Comment by arthuravianna** [comment] 2023-07-06 23:11
Hello, tuler.
The point is that if someone tries to follow the rollups-examples instructions to deploy a DApp on testnet it simply won't work. Based on this I decided to made this "issue" (which I later discovered is just a change of version 0.9 framework) know by the community before people start to go to Discord seeking for help.
I would like to suggest that this topic were approached somehow, maybe with instructions in the README on why you need an Authority contract for yourself and how to deploy it or a change in the deployer to allow an extra parameter to deploy an Authority contract when deploying the DApp.

**Comment by claudioantonio** [comment] 2023-07-28 17:27
Hi @arthuravianna ! Thanks for the detailed issue report! ❤️ 

Hi @tuler @guidanoli @pedroargento!
Could any of you please provide the recipe to correctly handle the Authority setup when building/deploying the examples so I can update the README?

Cheers!
PS: @nicocartesi 👀

**Comment by tuler** [comment] 2023-07-28 18:05
I think we should add the `--consensusAddress` parameter explicity to the call of `cartesi/rollups-cli create`, coming from a required environment variable set by the person during deployment.

https://github.com/cartesi/rollups-examples/pull/27/files#diff-392dc45ab07db991e12e049a935f7e09bd6f08dfcf82aeb7ef913f40c0fa5278R25

**Comment by claudioantonio** [comment] 2023-08-03 19:56
Hi @gligneul (cc. @miltonjonat ) what do you think about it?

**Comment by gligneul** [comment] 2023-08-03 21:01
I agree with Danilo.

**Comment by miltonjonat** [comment] 2023-08-07 19:15
First of all, I believe there is once again some effort duplication with Sunodo here. So I wouldn't want us to do spend too much time here.

Now, if the general belief (according to DevRel + Prototyping) is that the expectation of rollups-examples users is to run their own validators, then this should be the default behavior. I'm not sure if adding a `--consensusAddress` parameter achieves this by itself. Wouldn't we need some additional deploy script to deploy a new Authority (with the user's account as owner) and then have a way of using that authority address in the cli `--consensusAddress` param?

(sorry if I'm missing something)

**Comment by tuler** [comment] 2023-08-07 21:05
My point was only that forcing the `--consensusAddress` will expose what we really need, like what you said, create authority, etc.

**Comment by miltonjonat** [comment] 2023-08-08 12:18
Yeah, but will there be a practical way for people to do that? If we don't want to spend time tweaking the deploy script to deploy an Authority too, I guess we would need to at least add README instructions about how to deploy an Authority, right?

Or.. we could stop all this and move the examples to Sunodo right away.. What do you guys think?

**Comment by miltonjonat** [comment] 2023-08-23 20:16
Closed by #33

**Closed by miltonjonat** 2023-08-23 20:16 UTC
